name: Publish
on:
  workflow_dispatch:
concurrency:
  group: publish
  cancel-in-progress: true
permissions: write-all
jobs:
  publish-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tools/prebuild.sh
      - uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/action@v1
        with:
          base-path-to-features: src
          generate-docs: true
      - uses: stefanzweifel/git-auto-commit-action@v4
