name: Publish
on:
  workflow_dispatch:
concurrency:
  group: publish
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tools/prebuild.sh
      - uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
