name: Update index
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - CONTRIBUTING.md
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/update-index.yml"
  schedule:
    # https://crontab.guru/daily
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-index:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: oras-project/setup-oras@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: deno run -A main.ts
