name: Update feature collection index
on:
  schedule:
    # https://crontab.guru/daily
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_call:
jobs:
  update-feature-collection-index:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: denoland/setup-deno@v1
      - run: deno run -A main.ts
