name: Update index
on:
  schedule:
    # https://crontab.guru/daily
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-index:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno run -A .github/workflows/update-index.ts
